config/routes.rb
ProgettoLinguaggi2::Application.routes.draw do
  root to: 'pages#home'
  
  resources :groups 
  resources :groupships 
  resources :tags
  resources :usertags
  resources :users do
    member do
      get :messages
    end
    collection do
      get :search 
      get :search_tag
      get :search_category
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :calendars
  
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/vetrina_lavori', to: 'pages#vetrina_lavori'
  match '/ricerca_utenti', to: 'users#search'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :sender, :recipient, :id, :subject, :body
  
  is_private_message
  # The :to accessor is used by the scaffolding,
  # uncomment it if using it or you can remove it if not
  #attr_accessor :to
  belongs_to :users
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy


  def new
    @message = Message.new
    @user = User.find(params[:user])
    if @message.invite == true
      @group = Group.find(params[:group_id])
    end
   @message.invite = false
  end

  def create
    @message = Message.new
    @message.sender = User.find_by_name(params[:message][:sender])
    @message.recipient = User.find_by_name(params[:message][:recipient])
    @message.subject = params[:message][:subject]
    @message.invite = params[:message][:invite]
    if @message.invite == true
      @group = Group.find(params[:message][:group_id])
      @message.body = @group.id
    else
      @message.body = params[:message][:body]
    end
    if @message.save
      flash[:success] = "Messaggio inviato"
      redirect_to search_users_path(params[:message][:group_id])
    else
      render :action => :new
    end
  end

  def show
    @message = Message.find(params[:id])
  end  

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to user_path(current_user.id) 
  end

private

  def correct_user
      @message = current_user.messages.where(:recipient_id => current_user)
      redirect_to root_path if @message.nil?
  end
end

app/views/messages/_message.html.erb
<li>
  <span class="content">
  	<h4 class="formMessage">Da: </h4>
  	<h3 class="formMessage3"><%= link_to message.sender.name, new_message_path(:user => message.sender.id) %></h3>
  </br>
  	<h4 class="formMessage">Oggetto:  </h4>
  	<h3 class="formMessage3"><%= link_to message.subject, message_path(message.id) %></h3>
  	
  	<%= link_to "Elimina", message, :method => :delete, class: "btn btn-small btn-danger" %>
  	</span>
  

</li>


app/views/messages/new.html.erb
<%= provide(:title, 'Nuovo messaggio') %>
<h1>Nuovo messaggio</h1>
	<div id="form-messaggio">
		<%= form_for(@message) do |f| %>
			<% if signed_in? %>
				<%= f.hidden_field :sender, :value => current_user.name %>
			<%else%>
				<%= f.hidden_field :sender, :value => "utente usterno"%>
			<%end%>
		
			<h3>Messaggio per  <%= @user.name %></h3> 
			<%= f.hidden_field :recipient, :value => @user.name %>
			<%= f.hidden_field :invite, :value => false %>
			</br>
			
			<h3>Oggetto</h3>
			<%= f.text_field :subject, :value => params[:subject]%>
			
			<h3>Messaggio</h3>
			<%= f.text_field :body %><br>
			<%= f.submit "Invia", class: "btn btn-large btn-primary" %>
		
		<% end %>
	
	</div>


app/views/messages/show.html.erb
<div id="rispondi">

	<h4 class="formMessage">Da:  </h4>
	<h3 class="formMessage3"><%= @message.sender.name %></h3>
</br>
	<h4 class="formMessage">Oggetto:  </h4>
	<h3 class="formMessage3"><%= @message.subject %></h3>
</br>
	<% if @message.subject=="Invito" 
		then @message.body = link_to 'Unisciti', new_groupship_path(:group_id => @message.body)%>
	<%end%>
	<h4 class="formMessage">Messaggio:  </h4>
	<h3 class="formMessage3"><%= @message.body %></h3>
	</br>
</br>
	<%= link_to 'Rispondi', new_message_path(:user => @message.sender.id, :subject =>"Re: "+ @message.subject), class: "btn btn-large btn-success" %>
	<%= link_to "Elimina", @message, :method => :delete, class: "btn btn-large btn-danger" %>

</div>
<br/>
