config/routes.rb
ProgettoLinguaggi2::Application.routes.draw do
  root to: 'pages#home'
  
  resources :groups 
  resources :groupships 
  resources :tags
  resources :usertags
  resources :users do
    member do
      get :messages
    end
    collection do
      get :search 
      get :search_tag
      get :search_category
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :calendars
  
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/vetrina_lavori', to: 'pages#vetrina_lavori'
  match '/ricerca_utenti', to: 'users#search'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :skill, :training, :hobby, :work, :id, :name, :email, :password
  has_secure_password

  has_private_messages

  has_many :microposts, dependent: :destroy #ogni utente può avere più mivropost, se ut cancellato si cancellano anche i suoi post
  has_many :groups, dependent: :destroy
  has_many :groupships
  has_many :groups, :through => :groupships
  has_many :tags, :through => :usertags #ognuno può avere tanti tag 
  has_many :usertags
  has_many :messages, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  
  before_save :create_remember_token

  validates :name, presence:true, length: { maximum: 50 }
  validates :id, presence:true
  validates :password, length: { minimum: 6 }
  validates :skill, presence:true
  validates :training, presence:true
  validates :hobby, presence:true
  validates :work, presence:true
  validates :work, presence:true
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    
  def feed
    # This is preliminary.
    Micropost.where("user_id = ?", id)
  end
  
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%") 
    else
      scoped
    end
  end

private

    def create_remember_token
      # in Ruby 1.8.7 you should use SecureRandom.hex here instead
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
 
  def show
    @user = User.find(params[:id])
    @usertag=Usertag.all
    @tag=Tag.all
    #mi mostra il profilo dell'utente loggato
  end
  
  def new
    @user = User.new
  end
  #crea la sessione per l'utente che si logga sennò da errore
	def create
      user = User.find_by_email(params[:session][:email])
      if user && user.authenticate(params[:session][:password])
        sign_in user
        redirect_back_or user
      else
        flash.now[:error] = 'Invalid email/password combination'
        render 'new'
      end
  end
  #seleziona l'utente da modificare
  def edit
    @user = User.find(params[:id])
  end
   #per aggiornare le proprietà dell'utente
  def update
    @user = User.find(params[:id])
      @user.update_column(:work, params[:user][:work])
      @user.update_column(:training, params[:user][:training])
      @user.update_column(:skill, params[:user][:skill])
      @user.update_column(:hobby, params[:user][:hobby])
    
      redirect_to @user
  end
  
  def search
    if params[:format].nil?
      @group = nil
      @users = User.search(params[:search]).paginate(:page => params[:page])
    else     
      @group = Group.find(params[:format])
      @users = User.search(params[:search]).paginate(:page => params[:page])
    end
  end
 
  def search_tag
    if !current_user.nil?
    @users = User.find(:all,
                     :joins => "INNER JOIN usertags ON users.id = usertags.user_id
                                INNER JOIN tags on tags.id = usertags.tag_id",
                     :conditions => ["LOWER(tags.name) LIKE ? AND users.id IS NOT ?", params[:name], current_user.id])
    else
    @users = User.find(:all,
                     :joins => "INNER JOIN usertags ON users.id = usertags.user_id
                                INNER JOIN tags on tags.id = usertags.tag_id",
                     :conditions => ["LOWER(tags.name) LIKE ? ", params[:name]])
    end                   
  end
  
  def search_category
    if !current_user.nil?
    @users = User.uniq.find(:all,
                     :joins => "INNER JOIN usertags ON users.id = usertags.user_id
                                INNER JOIN tags on tags.id = usertags.tag_id",
                     :conditions => ["LOWER(tags.category) LIKE ? AND users.id IS NOT ?", params[:category], current_user.id])
    else
          @users = User.uniq.find(:all,
                     :joins => "INNER JOIN usertags ON users.id = usertags.user_id
                                INNER JOIN tags on tags.id = usertags.tag_id",
                     :conditions => ["LOWER(tags.category) LIKE ?", params[:category]])
    end
  end
  
  def messages
    @title = "Messaggi ricevuti"
    @user = User.find(params[:id])
    @messages = @user.received_messages 
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
  
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar (http://gravatar.com/) for a given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def group_admin_profile(user)
    nomegruppo = Group.where(:admin => user).pluck(:id)
    Group.find(nomegruppo)
  end

  def group_admin(user, group)
    Group.where(:admin => user, :id => group).count
  end
  
  def group_members(group)
        usersid = Groupship.where(:group_id => group).pluck(:user_id)
        User.find(usersid)
  end
  
  def name(id)
    User.find(params[:id])
  end
  
  def groupship(group_id, user_id)
    usersid = Groupship.where(:group_id => group_id)
    userid = usersid.where(:user_id => user_id)
    Groupship.find(userid)
  end

  
end

app/views/users/_user.html.erb
<% if user != current_user%>
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
 <br/>
<% if !@group.nil? && invited_user(@group.id, user.id)==0%>
	<% if pending_request(@group.id, user.id)==0%>
			<%= form_for Message.new do |f| %>
			<%= f.hidden_field :sender, :value => current_user.name %>
			<%= f.hidden_field :recipient, :value => user.name %>
			<%= f.hidden_field :subject, :value => "Invito"%>
			<%= f.hidden_field :invite, :value => true%>
			<%= f.hidden_field :group_id, :value => @group.id %><br/>
			<%= f.submit "Invita", class: "btn btn-medium btn-info" %>
			<%end%>
	<%else%>
	<h5 id="attesa">Utente in attesa di conferma</h5>
	<%end%>
<%end%>
</li>
<%end%>

app/views/users/edit.html.erb
<% provide(:title, "Modifica utente") %> 
<h1>Aggiorna il profilo</h1>
	<div id="change-image">
      	    <%= gravatar_for @user %>
      	    <%= link_to "Cambia immagine", "http://gravatar.com/emails", class:"btn btn-warning" %>
 	</div>
	<div id="info">
		<%= form_for(@user) do |f| %>
      		<%= render 'shared/error_messages', object: f.object %>
	      	<div id="modifica">
	      		<%= f.submit "Salva modifiche", class: "btn btn-medium btn-primary" %>
			</div>

		  	<ul class="nav nav-tabs" id="myTab">
					<li class="active"><a href="#portfolio">Portfolio</a></li>
					<li><a href="#formazione">Formazione</a></li>
					<li><a href="#competenze">Competenze</a></li>
					<li><a href="#esperienze">Esperienze Lavorative</a></li>
					<li><a href="#interessi">Interessi</a></li>
					<li><a href="#tag">Tag</a></li>
			</ul>
	 		<div class="tab-content">
	 		<div class="tab-pane active" id="portfolio">
					<iframe width="300" height="169" src="http://www.youtube.com/embed/cJOZp2ZftCw" frameborder="0" allowfullscreen></iframe>							
					<p>Video realizzato per il corso di effetti speciali.</p>
			</div>

			<div class="tab-pane" id="formazione">
				<%= f.text_area :training%>
 			</div>
			<div class="tab-pane" id="competenze">
				<%= f.text_area :skill%>
 			</div>
			<div class="tab-pane" id="esperienze">
				<%= f.text_area :work%>
 			</div>
			<div class="tab-pane" id="interessi">
				<%= f.text_area :hobby%>
			</div>
			<div class="tab-pane" id="tag">
				<%= render 'tags/list'%>
				<%= link_to "Modifica tag",   tags_path, class: "btn btn-small btn-warning"%>
			</div>
		</div>
		
		<script>  
		    $('#myTab a').click(function (e) {
	    e.preventDefault();
	    $(this).tab('show');
	    })
	    </script>
    <% end %>

	</div>

app/views/users/messages.html.erb
<%= provide(:title, 'Messaggi') %>
<div id="messaggi">
	<h1><%= @title %></h1>
	<ul>
		<%= render @messages %>
	</ul>

</div>

app/views/users/search.html.erb
<% provide(:title, 'Ricerca_utenti')%>
<% if @group.nil?%>
	<% if @users.length != 0 %> <!-- se ci sono degli utenti che corrispondono alla ricerca mostrali sennò stampa messagggio-->
		<% if @users.include?(current_user)%>
			<h1>CineMates</h1>
			<%= will_paginate %>
		<%else%>
			<h1>Trovati <%= pluralize(@users.length, "CineMates") %></h1>
			<%= will_paginate %>
		<%end%>
	<% else %>
		<h1>Nessun CineMates corrisponde alla tua ricerca</h1>
	<% end %>
<%else%>
<h1>Aggiungi CineMates al gruppo <%= @group.name%></h1>
<%= will_paginate %>
<% end %>

<%= render 'shared/search_form'%>
<div id="ricerca">
	<ul class="users">
		<%= render @users %>
	</ul>
</div>



app/views/users/search_category.html.erb
<% provide(:title, 'Ricerca_utenti')%>
<% if @users.length != 0 %> <!-- se ci sono degli utenti che corrispondono alla ricerca mostrali sennò stampa messagggio-->
	<h1>Trovati <%= pluralize(@users.length, "CineMates") %></h1>

<% else %>
	<h1>Nessun CineMates corrisponde alla tua ricerca</h1>
<% end %>
<span class="ricerca">
	<ul class="users">
		<%= render @users %>
	</ul>

</span>
<%= render 'shared/search_form'%>

app/views/users/search_tag.html.erb
<% provide(:title, 'Ricerca_utenti')%>
<% if @users.length != 0 %> <!-- se ci sono degli utenti che corrispondono alla ricerca mostrali sennò stampa messagggio-->
	<h1>Trovati <%= pluralize(@users.length, "CineMates") %></h1>

<% else %>
	<h1>Nessun CineMates corrisponde alla tua ricerca</h1>
<% end %>
<span class="ricerca">
	<ul class="users">
		<%= render @users %>
	</ul>
</span>
<%= render 'shared/search_form'%>


app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
			<span class="span1">
				<%= gravatar_for @user %>
			</span>
			<h1 id="user_name"><%= @user.name %></h1>
			
			<% if current_user?(@user)%>
				<h3><%= render 'shared/stats'%></h3>

				<div id="modifica">
					<%= link_to 'Modifica profilo', edit_user_path(@user.id), class: "btn btn-medium btn-primary" %>
				
				</div>
			<%else%>
			<div id="inviamessaggio">
				<% if signed_in? %>
			  	<%= link_to 'Invia messaggio', new_message_path(:user => @user.id), class: "btn btn-medium btn-primary" %>
			  	<%end%>
			</div>
			<% end %>

<div id="profilo">
	<div id="info">
		<ul class="nav nav-tabs" id="myTab">
			<li class="active"><a href="#portfolio">Portfolio</a></li>
			<li><a href="#formazione">Formazione</a></li>
			<li><a href="#competenze">Competenze</a></li>
			<li><a href="#esperienze">Esperienze Lavorative</a></li>
			<li><a href="#interessi">Interessi</a></li>
			<li><a href="#tag">Tag</a></li>
		</ul>
		
	 	<div class="tab-content">
	 		<div class="tab-pane active" id="portfolio">
	 			<iframe width="300" height="169" src="http://www.youtube.com/embed/cJOZp2ZftCw" frameborder="0" allowfullscreen></iframe>
		    		<div id="descrizione-video">Video realizzato per il corso di Effetti Speciali.
					</div>
			</div>
			<div class="tab-pane" id="formazione">
				<h4><%= @user.training %></h4>
			</div>
			<div class="tab-pane" id="competenze">
				<h4><%= @user.skill %></h4>
			</div>
			<div class="tab-pane" id="esperienze">
				<h4><%= @user.work %></h4>
			</div>
			<div class="tab-pane" id="interessi">
				<h4><%= @user.hobby %></h4>
			</div>
			<div class="tab-pane" id="tag">
	   
	            <%= render 'tags/list'%>
		    
			    <div id="modifica_tag">
			    	<% if current_user?(@user)%>
						<h4><%= link_to 'Modifica Tag', tags_path, class: "btn btn-mini btn-warning" %></h4>
						<%end%>
			    
				</div>
			</div>
				
		</div>
	</div>
		<script>  
		    $('#myTab a').click(function (e) {
	    e.preventDefault();
	    $(this).tab('show');
	    })
	    </script>
	<br/>
	
	<% if !current_user?(@user)%>
		<% if !group_admin_profile(@user.id).nil?%>
			<div class="well" id="gruppi">
				<h1>Gruppi creati:</h1>
				<% @groups = group_admin_profile(@user.id)%>
				<%= render @groups%>
			</div>
		<%end%>
	<%end%>
	<div id="awards"> 
		<%= image_tag ("awards.png") %>
	</div>
</div>
