config/routes.rb
ProgettoLinguaggi2::Application.routes.draw do
  root to: 'pages#home'
  
  resources :groups 
  resources :groupships 
  resources :tags
  resources :usertags
  resources :users do
    member do
      get :messages
    end
    collection do
      get :search 
      get :search_tag
      get :search_category
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :calendars
  
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/vetrina_lavori', to: 'pages#vetrina_lavori'
  match '/ricerca_utenti', to: 'users#search'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_error_messages.html.erb
<% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
<% end %>


app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <!--prende i singoli micropost e me li elenca-->
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method:  :delete,
                                     confirm: "You sure?",
                                     title:   feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :content, placeholder: "Aggiungi un micropost" %>
    <%= f.hidden_field :group_id, :value => @group.id %>
  <%= f.submit "Post", class: "btn btn-large btn-info" %>
<% end %>

app/views/shared/_search_form.html.erb
</span>
<span id="formricerca">
	<ul class="search">
		<li id="cercaNome">
			<%= form_tag search_users_path, :method => 'get', :class => 'form-search' do %>
	  			<p>
	    			<%= text_field_tag :search, params[:search], :class => 'input-medium search-query', placeholder:"Ricerca per nome"  %>
	    			<%= submit_tag "Cerca", :name => nil, :class => 'btn' %>
	  			</p>
	  		<% end %>
	  	</li>
	  	
		<li id="cercaTag">
			<%= form_tag search_tag_users_path, :method => 'GET', :class => 'form-item-be form-search’' do %>
	  			<p>
	    			<%= select_tag "name", options_from_collection_for_select(Tag.select(:name).uniq, "name", "name" ), {:prompt => "Ricerca per tag"}%>	
					<%= submit_tag "Cerca", :name => nil, :class => 'btn' %>
	  			</p>
	  		<%end%>
	  	</li>
	  	
		<li id="cercaCategoria">
			<%= form_tag search_category_users_path, :method => 'GET', :class => 'form-item-be form-search’' do%>
	  			<p>
	  				<%= select_tag "category", options_from_collection_for_select(Tag.select(:category).uniq, "category", "category" ), {:prompt => "Ricerca per categoria"}%>	
					<%= submit_tag "Cerca", :name => nil, :class => 'btn' %>
	  			</p>
	  		<%end%>
	  	</li>
	</ul>
</span>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
	<a href="<%= messages_user_path(@user) %>">
		<div id="count-message">
		<%= @user.unread_message_count %> messaggi ricevuti
		</div>
		<div id="messages">
		<%= image_tag ("mail.jpg") %>
		</div>
	</a>