config/routes.rb
ProgettoLinguaggi2::Application.routes.draw do
  root to: 'pages#home'
  
  resources :groups 
  resources :groupships 
  resources :tags
  resources :usertags
  resources :users do
    member do
      get :messages
    end
    collection do
      get :search 
      get :search_tag
      get :search_category
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :calendars
  
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/vetrina_lavori', to: 'pages#vetrina_lavori'
  match '/ricerca_utenti', to: 'users#search'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_body.html.erb
<body class="body">
	<div id="content">
  		<div id="wrapper">
  			<%= yield %>
		</div>
    </div>          
</body>


app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  	 <div id="content">
  	<div id= "navigation">
  		<ul>
           <%if signed_in?%>
             <li><%= link_to "Gruppi",   groups_path %></li>
             <li><%= link_to "Vetrina",   vetrina_lavori_path %></li>
			 <li><%= link_to "Utenti",   search_users_path %></li>
             <li><%= link_to "Profilo",   current_user %></li>
        	 <li><%= link_to "Esci",   signout_path, method: "delete" %>
	       
			<%else%>
	      
			<li><%= link_to "Home",   home_path %></li>
            <li><%= link_to "Chi siamo",   about_path %></li>
            <li><%= link_to "Utenti",   search_users_path %></li>
            <li><%= link_to "Vetrina",   vetrina_lavori_path %></li>
            <li><%= link_to "Entra",   signin_path %></li>
			<%end%>
       </ul>        
    </div>      
	</div>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
	<!--<div class="navbar-inner">-->
		<div class="container-fluid">
			<nav>
				<div class="img_logo">
					<%= image_tag ("LOGO.png") %>
				</div>
			</nav>
		</div>
	<!--</div>-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= titolo_intero(yield(:title)) %></title>
   
 	 <%= stylesheet_link_tag "application", :media =>"screen and (min-width:481px)" %>
 	 <%= stylesheet_link_tag "application", :media =>"screen and (max-width:480px)" %>
 	 
 	 <%= javascript_include_tag 'jquery', 'rails', 'application' %>

	 <%= csrf_meta_tags %>
</head>
<body>
	    <%= render 'layouts/header' %> 
		<%= render 'layouts/body' %>
	  	<%= render 'layouts/footer' %>
	  	
        <%= debug(params) if Rails.env.development? %> 
	  	
</body>
</html>